INSERT INTO myghtyboard_category VALUES (1, 1, 'First Category', 0),
(2, 1, 'Second Category', 0);
INSERT INTO myghtyboard_forum VALUES (1, 1, 1, 'First Forum', 'A forum', 2, 4, 'piotr<br>2006-09-04 15:56:29<br><a href="/forum/topic/1/2/">Frugalware Topic</a>', 0),
(2, 1, 1, 'Second Forum', 'A description', 0, 0, NULL, 1),
(3, 1, 2, 'Extra Forum', 'Some text here :)', 0, 0, NULL, 0);
INSERT INTO myghtyboard_post VALUES (1, 1, 1, 'This is a test topic\r\n\r\n:twisted::grin:', 'piotr', '2006-09-04 15:55:00', '127.0.0.1', 'localhost.localdomain'),
(2, 1, 1, 'and a test reply!', 'piotr', '2006-09-04 15:55:11', '127.0.0.1', 'localhost.localdomain'),
(3, 1, 2, 'Miklos Vajna has announced the second release candidate of Frugalware Linux 0.5, the last development build before the stable release, expected at the end of September: "The Frugalware Developer Team is pleased to announce the immediate availability of Frugalware 0.5rc2, the second release candidate of the upcoming 0.5 stable release. A short and incomplete list of changes since 0.5rc1: updated GNOME to 2.16 Release Candidate (2.15.92); ~300 bugfixes; updated KDE and GRUB artwork; more than 30 new packages: ntfs-3g, avifile, gnome-sharp and many more!" Here is the brief release announcement. Download (SHA1): frugalware-0.5rc2-i686-dvd1.iso (4,264MB).', 'piotr', '2006-09-04 15:56:12', '127.0.0.1', 'localhost.localdomain'),
(4, 1, 2, '<blockquote><b>piotr wrote:</b><br><cite>Mikos Vajna has announced the second release candidate of Frugalware Linux 0.5, the last development build before the stable release, expected at the end of September: "The Frugalware Developer Team is pleased to announce the immediate availability of Frugalware 0.5rc2, the second release candidate of the upcoming 0.5 stable release. A short and incomplete list of changes since 0.5rc1: updated GNOME to 2.16 Release Candidate (2.15.92); ~300 bugfixes; updated KDE and GRUB artwork; more than 30 new packages: ntfs-3g, avifile, gnome-sharp and many more!" Here is the brief release announcement. Download (SHA1): frugalware-0.5rc2-i686-dvd1.iso (4,264MB).</cite></blockquote>\r\nTollef Fog Heen has announced the second alpha release (also known as "Knot") of Ubuntu 6.10, code name "Edgy Eft": "Welcome to Edgy Eft Knot 2, which will in time become Ubuntu 6.10. The primary changes from Knot 1 have been implementations of feature goals as listed on this page. Common to all variants, we have upgraded X.Org to the 7.1 release. In Ubuntu, GNOME has been updated to 2.16.0 Release Candidate 1. Other notable changes are listed here. KDE has been updated to 3.5.4. Other notable Kubuntu changes are listed here." Read the full release announcement for further information and a list of up-to-date download mirrors. As always, the full range of live and installation CDs for various architectures is available for download from the project''s main server; here is a quick link to the i386 Desktop CD: edgy-desktop-i386.iso (666MB, MD5). Kubuntu 6.10 Knot 2 CDs have also been released.', 'piotr', '2006-09-04 15:56:29', '127.0.0.1', 'localhost.localdomain');
INSERT INTO myghtyboard_topic VALUES (1, 1, 1, 'A test topic', 'piotr', 2, 'piotr<br>2006-09-04 15:55:11', '2006-09-04 15:55:11'),
(2, 1, 1, 'Frugalware Topic', 'piotr', 2, 'piotr<br>2006-09-04 15:56:29', '2006-09-04 15:56:29');
