def render(dic, text):
	s = 1
	for i in dic:
		text = text.replace(i['tag'], '<a name="' + str(s) +'" href="' +  i['attributes']['id'] + '" title="' + i['code'] + '"></a><h2>' + i['code'] + '</h2>')
		s = s+1
	return text

def describe():
	return {'tag':'h', 'tag_example':_('[rk:h id="1-4"]Title[/rk:h]'), 'description':_('Will insert the given title in a H1-4 tag (as defined in the id attribute). Use this tags if you want to use Page Table of Contents generated by [toc]')}

